### PR TITLE
WIP (not for merge, only discussion)

### PR DESCRIPTION
**Pull request by sjsrey**
Just to give you and idea of the outline for the ESDA notebook - no narrative here just trying to work with the berlin data and stub out the flow.

Tomorrow I will (after hearing from you) flesh out the mapclassification stuff, detail narrative for all components.

I hope this will then feed into what you have planned for the regression part. We could go with some regionalization after this if not?

### CODE REVIEW

**Comment by ljwolf** [comment]
Great, sounds good!

You might want to use `sbn.regplot(..., ci=None)` for the moran regression line? That way it's just direct to the regressoin plot, unless you want to walk through the actual regression fit for OLS Moran stuff.

**Comment by ljwolf** [comment]
Also, notedown has md -> notebook?? That's awesome .

**Comment by ljwolf** [comment]
I think this might conflict with #4, since I rev `sds1` there. If we merge this then that, it should be fine.

**Comment by sjsrey** [comment]
I'm moving to the airport. sds2 and sds3 are good to go.

**Comment by ljwolf** [comment]
Ace, great, thanks!

**Comment by sjsrey** [comment]
just a quick note, when i pull these back down i have to reprocess the md -> nb step. trying to open the downloaded nb throws an error about not recognizing things.

**Comment by ljwolf** [comment]
They should be fixed?

**Comment by ljwolf** [comment]
I screwed it up the first time; didn't use `--to notebook`.

**Pull request merged**
